import { Direccion, Escena } from "./../types/src.types.js";
export const INFURA_GATEWAY: string = "https://thedial.infura-ipfs.io";
export const SCENE_LIST: Escena[] = [
  {
    key: "estudio",
    world: { height: 830, width: 1512 },
    fondo: {
      uri: "QmQho15EawdPjxhZ6QcnFoGHiEV8r2dTS1u7TczQv9cd44",
      etiqueta: "fondo",
      displayHeight: 830,
      displayWidth: 1512,
      sitio: { x: 0, y: 0 },
    },
    cover: "",
    sillas: [
      {
        anim: Direccion.Sofa,
        profundidad: false,
        adjustedX: 800,
        adjustedY: 210,
        etiqueta: "sofaUno",
        sitio: { x: 779, y: 200 },
        talla: { x: 197, y: 107 },
        uri: "QmQfqKAD2Hepe9kQ9VxBSNmwZrywCvuPrnAr5AiF4bMvwB",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
      {
        anim: Direccion.Sofa,
        profundidad: false,
        adjustedX: 1250,
        adjustedY: 200,
        etiqueta: "sofaDos",
        sitio: { x: 1250, y: 200 },
        talla: { x: 194, y: 109 },
        uri: "QmUFsXQpp1ZZWKWCnHAED4pgZgeLSBnp4ofMz9ae1BkhAR",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
      {
        anim: Direccion.Silla,
        profundidad: true,
        adjustedX: 1330,
        adjustedY: 280,
        etiqueta: "silla1",
        sitio: { x: 1322, y: 325 },
        talla: { x: 92, y: 116 },
        uri: "QmariT81Kgxw4mNHCt8wGHmgH5avzrZt2r6vNiik4qeSwK",
        escala: { x: 1, y: 1 },
        par: "escritorio1",
      },
      {
        anim: Direccion.Silla,
        profundidad: true,
        adjustedX: 1330,
        adjustedY: 420,
        etiqueta: "silla2",
        sitio: { x: 1322, y: 470 },
        talla: { x: 89, y: 109 },
        uri: "Qmc8VyBMDALMJJknadELsL9SBQuYSuTHpa3e1SqfX61Egn",
        escala: { x: 1, y: 1 },
        par: "escritorio2",
      },
      {
        anim: Direccion.Silla,
        profundidad: true,
        adjustedX: 1000,
        adjustedY: 285,
        etiqueta: "silla3",
        sitio: { x: 993, y: 325 },
        talla: { x: 100, y: 108 },
        uri: "QmUuHUnrMHhusH1JrgG6WonoCUxG1t7LQe348gru2d4uHM",
        escala: { x: 1, y: 1 },
        par: "escritorio3",
      },
      {
        anim: Direccion.Silla,
        profundidad: true,
        adjustedX: 1000,
        adjustedY: 440,
        uri: "QmfZPky9neYWSuQcZ7wtyajqMCRPBaq7WiPjaab4ZxC8PZ",
        etiqueta: "silla4",
        sitio: { x: 999, y: 485 },
        talla: { x: 98, y: 103 },
        escala: { x: 1, y: 1 },
        par: "escritorio4",
      },
    ],
    objects: [
      {
        etiqueta: "pared",
        sitio: { x: 850, y: 110 },
        talla: { x: 1022, y: 204 },
        uri: "QmcR8PpyDhRaUzJJW5UoxhnyzqNk88imgXS2MGuhgfYsYK",
        escala: { x: 1.3, y: 1.1 },
        profundidad: 0,
      },
      {
        etiqueta: "nevera",
        sitio: { x: 145, y: 205 },
        talla: { x: 235, y: 371 },
        uri: "QmaGoMNwYt7aEgG6AoKGmDdmWUQgshQ8KtASkgoHKgmcS2",
        escala: { x: 1.3, y: 1.1 },
        profundidad: 0,
      },
      {
        etiqueta: "maquina",
        sitio: { x: 470, y: 200 },
        talla: { x: 106, y: 225 },
        uri: "QmVubKFGVcdfZS2pSEhmK8DtpFWbiC8H2BX11VPTd9xnNp",
        escala: { x: 1.6, y: 1.1 },
        profundidad: 0,
      },
      {
        etiqueta: "alfombra",
        sitio: { x: 410, y: 520 },
        talla: { x: 246, y: 179 },
        uri: "QmQaZhrMnuwkKbP2UbYtnMxRiUcpZfNGyuEhGuqd7xcFAj",
        escala: { x: 1.5, y: 1.2 },
        profundidad: 0,
      },
      {
        etiqueta: "arcade",
        sitio: { x: 1442, y: 700 },
        talla: { x: 163, y: 267 },
        uri: "QmaNMrJo7TqEpvsveTFJk7zwBbS4SukM3gnuVwhiY5sCoa",
        escala: { x: 1, y: 1 },
      },
      {
        etiqueta: "audio1",
        sitio: { x: 756, y: 772 },
        talla: { x: 160, y: 117 },
        uri: "QmYrGLoU35kwH9HyVLi283hG2GzX1fbxuszHT3j1qfAs8G",
        escala: { x: 1, y: 1 },
        profundidad: 1000,
      },
      {
        etiqueta: "audio2",
        sitio: { x: 916, y: 765 },
        talla: { x: 160, y: 117 },
        uri: "QmQA2cgeuAMvLSqj75CWrhmNhKoQV2GKapy94Co6WmWQVi",
        escala: { x: 1, y: 1 },
        profundidad: 1000,
      },
      {
        etiqueta: "planta1",
        sitio: { x: 530, y: 788 },
        talla: { x: 97, y: 84 },
        uri: "QmXYg1FC5zTHXHP1czJmsusC9DT33JCwHnLacYAui1HH84",
        escala: { x: 1, y: 1 },
        profundidad: 1000,
      },
      {
        etiqueta: "planta2",
        sitio: { x: 605, y: 779 },
        talla: { x: 75, y: 104 },
        uri: "QmdcSwsasjt18R7Hey77X6idnW9qz25Q1XkVsHT7inqbm7",
        escala: { x: 1, y: 1 },
        profundidad: 1000,
      },
      {
        etiqueta: "capsula",
        sitio: { x: 50, y: 468 },
        talla: { x: 95, y: 302 },
        uri: "QmYjXKxmyRQHf6fDdqEaNPEdc3W7gcFuNxogsVL38kR3M9",
        escala: { x: 1, y: 1 },
      },
      {
        etiqueta: "telefono",
        sitio: { x: 50, y: 710 },
        talla: { x: 86, y: 242 },
        uri: "QmSz2dcSRdX9vtxpXH91dS4pe8PAkAakbwfb4mGZNwunkk",
        escala: { x: 1, y: 1 },
      },
    ],
    profundidad: [
      {
        etiqueta: "panelDeControl",
        uri: "QmWMPF4YYvRLGW4F76kufDSxg2LnYojDNZK7cfdkwQxdXw",
        escala: { x: 1, y: 1 },
        sitio: { x: 1320, y: 630 },
        talla: { x: 390, y: 228 },
      },
      {
        etiqueta: "escritorio1",
        sitio: { x: 1342, y: 310 },
        talla: { x: 319, y: 186 },
        uri: "QmWtr9iRZ4HiPe1PBxrJfiB9hEQNa3GWxtipt7hqFvBPvs",
        escala: { x: 1, y: 1 },
      },
      {
        etiqueta: "escritorio2",
        sitio: { x: 1342, y: 430 },
        talla: { x: 307, y: 177 },
        uri: "QmTwbtXhizeCxBbZk9Nbd3yrt67kcB7Ytm6sKAzx5rFtCd",
        escala: { x: 1, y: 1 },
      },
      {
        etiqueta: "escritorio3",
        sitio: { x: 1013, y: 310 },
        talla: { x: 307, y: 165 },
        uri: "Qmcy6nTw4YaGj8AEtba2WVm8gYy1vj9LbyMNk9qGptz4ny",
        escala: { x: 1, y: 1 },
      },
      {
        etiqueta: "escritorio4",
        sitio: { x: 1019, y: 440 },
        talla: { x: 307, y: 160 },
        uri: "Qmd8VH1yPkPGtxoRM1bdAvLJnjyTG21pgswddCVnECxDHh",
        escala: { x: 1, y: 1 },
      },
    ],
    sprites: [
      {
        etiqueta: "muchacho",
        uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        x: 383,
        y: 576,
        cover: "QmZ4HicnNtbAV4HPikPFrnsWcREFVTa6q5cYQ1AoV3Qhp9",
        displayHeight: 600,
        displayWidth: 300,
        frameWidth: 600,
        frameHeight: 600,
        margin: 0,
        startFrame: 0,
        endFrame: 143,
        escala: { x: 0.5, y: 0.5 },
        maxMoves: 6,
      },
      {
        etiqueta: "chica",
        uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        x: 383,
        y: 576,
        cover: "QmZ4HicnNtbAV4HPikPFrnsWcREFVTa6q5cYQ1AoV3Qhp9",
        displayHeight: 600,
        displayWidth: 300,
        frameWidth: 600,
        frameHeight: 600,
        margin: 0,
        startFrame: 0,
        endFrame: 143,
        escala: { x: 0.5, y: 0.5 },
        maxMoves: 4,
      },
    ],
    prohibited: [
      { x: 0, y: 0, height: 150, width: 1512 },
      { x: 0, y: 0, height: 250, width: 250 },
      { x: 1349, y: 670, height: 200, width: 163 },
      { x: 357, y: 0, height: 190, width: 225 },
      { x: 0, y: 0, height: 830, width: 80 },
      {
        x: 1122,
        y: 590,
        height: 50,
        width: 390,
      },
      {
        x: 1182,
        y: 220,
        height: 100,
        width: 330,
      },
      {
        x: 1205,
        y: 350,
        height: 100,
        width: 330,
      },
      {
        x: 859,
        y: 220,
        height: 100,
        width: 330,
      },
      {
        x: 865,
        y: 360,
        height: 100,
        width: 350,
      },
      {
        x: 865,
        y: 360,
        height: 150,
        width: 10,
      },
      {
        x: 645,
        y: 0,
        height: 160,
        width: 350,
      },
      {
        x: 1075,
        y: 0,
        height: 160,
        width: 350,
      },
    ],
  },
  {
    key: "bolsa",
    world: { height: 830, width: 1512 },
    fondo: {
      uri: "QmTrhsok3TvKDRt1HqjCg5PpiANdcF49Whp2NNDXeshSuQ",
      etiqueta: "fondo",
      displayHeight: 830,
      displayWidth: 1512,
      sitio: { x: 0, y: 0 },
    },
    cover: "QmZR6JXmzwEUM1ouVh1LXoycYXWoZVtaRyWB7z28L8q2vV",
    objects: [
      {
        etiqueta: "ventanas",
        sitio: { x: 850, y: 110 },
        talla: { x: 1022, y: 204 },
        uri: "QmV1ozQMtiCyqSEGKxg63DDRwhL4wYCJqzegMheARrXjxW",
        escala: { x: 1.3, y: 1.1 },
        profundidad: 0,
      },
      {
        etiqueta: "monitor",
        sitio: { x: 145, y: 205 },
        talla: { x: 235, y: 371 },
        uri: "QmSUovQbp8JByka4Nk8t3DvxZ3kXgRuVU9kh67V5kn9YgG",
        escala: { x: 1.3, y: 1.1 },
        profundidad: 0,
      },
      {
        etiqueta: "escritoriosSuperior",
        sitio: { x: 470, y: 200 },
        talla: { x: 106, y: 225 },
        uri: "QmbW6NieKq5rkqE7F5UDyAVU2g9NF5WYAWCux7Qvuwuh54",
        escala: { x: 1.6, y: 1.1 },
        profundidad: 0,
      },
      {
        etiqueta: "escritoriosInferior",
        sitio: { x: 410, y: 520 },
        talla: { x: 246, y: 179 },
        uri: "QmTesaW8dD2pkTSsLvi6Nhsf3tXN9NQmfBfmMhLfht1abJ",
        escala: { x: 1.5, y: 1.2 },
        profundidad: 0,
      },
    ],
    sprites: [
      {
        etiqueta: "muchacho",
        uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        x: 383,
        y: 576,
        cover: "QmZ4HicnNtbAV4HPikPFrnsWcREFVTa6q5cYQ1AoV3Qhp9",
        displayHeight: 600,
        displayWidth: 300,
        frameWidth: 600,
        frameHeight: 600,
        margin: 0,
        startFrame: 0,
        endFrame: 143,
        escala: { x: 0.5, y: 0.5 },
        maxMoves: 6,
      },
      {
        etiqueta: "chica",
        uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        x: 383,
        y: 576,
        cover: "QmZ4HicnNtbAV4HPikPFrnsWcREFVTa6q5cYQ1AoV3Qhp9",
        displayHeight: 600,
        displayWidth: 300,
        frameWidth: 600,
        frameHeight: 600,
        margin: 0,
        startFrame: 0,
        endFrame: 143,
        escala: { x: 0.5, y: 0.5 },
        maxMoves: 4,
      },
    ],
    profundidad: [],
    prohibited: [],
    sillas: [
      {
        anim: Direccion.Silla,
        profundidad: false,
        adjustedX: 800,
        adjustedY: 210,
        etiqueta: "silla1",
        sitio: { x: 779, y: 200 },
        talla: { x: 197, y: 107 },
        uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
      {
        anim: Direccion.Silla,
        profundidad: false,
        adjustedX: 800,
        adjustedY: 210,
        etiqueta: "silla2",
        sitio: { x: 779, y: 200 },
        talla: { x: 197, y: 107 },
        uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
      {
        anim: Direccion.Silla,
        profundidad: false,
        adjustedX: 800,
        adjustedY: 210,
        etiqueta: "silla3",
        sitio: { x: 779, y: 200 },
        talla: { x: 197, y: 107 },
        uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
      {
        anim: Direccion.Silla,
        profundidad: false,
        adjustedX: 800,
        adjustedY: 210,
        etiqueta: "silla4",
        sitio: { x: 779, y: 200 },
        talla: { x: 197, y: 107 },
        uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
      {
        anim: Direccion.Silla,
        profundidad: false,
        adjustedX: 800,
        adjustedY: 210,
        etiqueta: "silla5",
        sitio: { x: 779, y: 200 },
        talla: { x: 197, y: 107 },
        uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
      {
        anim: Direccion.Silla,
        profundidad: false,
        adjustedX: 800,
        adjustedY: 210,
        etiqueta: "silla6",
        sitio: { x: 779, y: 200 },
        talla: { x: 197, y: 107 },
        uri: "QmYukvtXPobWiDUdFFCdSJLQ6Pga55unN3fFBAHNWKSprp",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
      {
        anim: Direccion.Silla,
        profundidad: false,
        adjustedX: 800,
        adjustedY: 210,
        etiqueta: "silla7",
        sitio: { x: 779, y: 200 },
        talla: { x: 197, y: 107 },
        uri: "QmYukvtXPobWiDUdFFCdSJLQ6Pga55unN3fFBAHNWKSprp",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
      {
        anim: Direccion.Silla,
        profundidad: false,
        adjustedX: 800,
        adjustedY: 210,
        etiqueta: "silla8",
        sitio: { x: 779, y: 200 },
        talla: { x: 197, y: 107 },
        uri: "QmYukvtXPobWiDUdFFCdSJLQ6Pga55unN3fFBAHNWKSprp",
        escala: { x: 1.2, y: 1.2 },
        depth: 0,
      },
    ],
  },
];
